---
title: "Project: Visual Analytics on Singapore Merchandise Trade"
description: |
  This is the Group 4 project website for the module "Visual Analytics and Applications" for the session 2021-2022 at the Singapore Management University. The project aims to use descriptive analysis, trend analysis and timeseries clustering techniques to study merchandise trade of Singapore with other countries for the period Jan 2018 (pre-covid) to Jan 2022 (post-covid) to find interesting insights on trade during the pandemic.
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

```
# Overview
The global economy was heavily impacted in 2020 to 2021 due to the lock downs, as people saw unprecedented disruption of daily lives. Based on the World Trade organisation report press release in Oct 2021 [here]( https://www.wto.org/english/news_e/pres21_e/pr889_e.htm), the World merchandise trade volume sank below 2015 levels in Q1 2020 and this observation applied to all the regions.

Singapore trades with more than a hundred countries and is one of the most trade-dependent economy globally. As a comparatively small and open economy, movements in demand and supply will critically impact the import-export balance it has established for itself as a major trading hub.  For the past 10 years, Singapore’s trade balance (the value of exports minus the value of imports) has been in surplus, even during the COVID years in 2020 and 2021. As at 2021, the country’s major trading partner is China, followed by Hong Kong.

The trade balances information is publicly available on the Singstat government website, however the table form does not provide sufficient visual representation for readers to compare across regions and across time. It is not clear if the number of trading partners and behaviour of trading with each partner remains the same pre and during COVID, hence this project aims to investigate if there were changes.

# Objective
This project aims to understand the pre-covid and during-covid,
*import and export levels of Singapore among the many trading country partners they have
*change in trading balance among significant trading partners through effective visualisation for comparison 
*any clustering patterns among the trading partners of Singapore across time. 

The second objective is to build an app to allow users to explore the data by selecting various countries /trading partners for comparison.
 
#Data source and Overview
This project uses the Merchandise Trade by Region/Market dataset from the Singapore’s Department of Statistics. [Click here to view the data set] (https://www.singstat.gov.sg/find-data/search-by-theme/trade-and-investment/merchandise-trade/latest-data).
The import data refers to all goods brought into Singapore, irrespective of whether they are for consumption, for processing, for use in manufacturing, or for subsequent re-shipment to other countries. The export data refers to all goods taken out of Singapore, which includes domestic exports and re-exports. All dollar values are shown in Singapore dollars

 
The metadata table of our main working file is shown below:
Country		
Month		
Year		
Import (SGD value in Thousands)		
Import (SGD value in Thousands)		


Visualisations


# Tools & Packages
Tidyverse
ggplot2
dtwclust

# Members
Farah Foo – [profile here](
Karishma Yadav – [profile here](
Tan Yan Ru – [profile here](

# References
https://oec.world/en/profile/country/sgp
https://www.mti.gov.sg/-/media/MTI/Resources/Economic-Survey-of-Singapore/2019/Economic-Survey-of-Singapore-First-Quarter-2019/FA_1Q19.pdf

