---
title: "Untitled"
description: |
  A new article created using the Distill format.
author:
  - name: Nora Jones 
    url: https://example.com/norajones
    affiliation: Spacely Sprockets
    affiliation_url: https://example.com/spacelysprokets
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, echo = TRUE, warning = FALSE, message = FALSE}
packages = c('rmarkdown','gganimate','shiny','tidyverse','shinydashboard','lubridate','plotly','leaflet','readr','crosstalk','shinythemes','sparkline','skimr','shinycssloaders','ggcorrplot','RColorBrewer','rgdal','vip','SnowballC','slam','zoo',"bslib", "ggplot2",
             "dtwclust", 'BBmisc', 'tibble', 'ggdendro',
             'rnaturalearth', 'rnaturalearthdata',
             'ggthemes', 'ggiraph', "shinyWidgets")

for(p in packages)
{
  if(!require(p,character.only = T))
  {
    install.packages(p)
  }
  library(p,character.only = T)
}
```


```{r, echo = TRUE, warning = FALSE, message = FALSE}
imports <- read_csv("data/imports.csv")
imports <- imports[,c(2:4)]
exports <- read_csv("data/exports.csv")
exports <- exports[,c(2:4)]
#view(imports)
#view(exports)
# binding data frames

trade <- inner_join(imports, exports, by = c('Time','Data Series')) 
trade <- na.omit(trade)
#view(trade)

```

```{r, echo = TRUE, warning = FALSE, message = FALSE}
trade$`Data Series`[trade$`Data Series`=="Slovak Republic (Slovakia) (Thousand Dollars)"] <- "Slovakia (Thousand Dollars)"
trade$`Data Series`[trade$`Data Series`=="Iran (Islamic Republic Of) (Thousand Dollars)"] <- "Iran (Thousand Dollars)"
trade <- trade %>% separate(`Data Series`, c("Country","Units"), " \\(")

trade$Year_Month <- trade$Time
trade <- trade %>% separate(Time, c("Year","Month"), " ")
#view(trade)
```


```{r, echo = TRUE, warning = FALSE, message = FALSE}
old <- c("Million Dollars)", "Thousand Dollars)")
new <- c(1000000,1000)
trade$multiple = (factor(trade$Units, old, new))

trade$multiple = as.numeric(as.character(trade$multiple))
```


```{r, echo = TRUE, warning = FALSE, message = FALSE}
trade <- trade %>%
            mutate(Imports = (Imports*multiple))
trade <- trade %>%
            mutate(Exports = (Exports*multiple))

trade <- trade %>%
            mutate(Net_Imports = (Exports-Imports))

trade <- trade %>%
            mutate(Trade_Volume = (Exports+Imports))
trade <- subset(trade, select = -c(Units, multiple))
```

```{r}
trade$Country[trade$Country=="Germany, Federal Republic Of"] <- "Germany"
trade$Country[trade$Country=="Laos People's Democratic Republic"] <- "Laos"
trade$Country[trade$Country=="Vietnam, Socialist Republic Of"] <- "Vietnam"
trade$Country[trade$Country=="Maldives, Republic Of"] <- "Maldives"
trade$Country[trade$Country=="Syrian Arab Republic"] <- "Syria"
trade$Country[trade$Country=="Republic Of Korea"] <- "South Korea"

Regions <- c('America','Asia', 'Oceania', 'Europe','Africa', 'European Union','Other Countries In Oceania','Germany, Democratic Republic Of',"Democratic People's Republic Of Korea","Yemen Democratic")
trade<-trade[!(trade$Country %in% Regions),]

```

```{r}
trade$Month <-  match(trade$Month,month.abb)
trade$Month <- sprintf("%02d", as.numeric(trade$Month))

trade$YearMonth <- paste(trade$Year,trade$Month,sep="-")
trade$YearMonth <- as.Date(as.yearmon(trade$YearMonth))
```

```{r}
trade<-transform(trade,Balance=ifelse(Net_Imports> 0,"Positive","Negative"))
#view(trade)
```
```{r}
time_order <- rev((unique(trade$Year_Month)))
trade$Year_Month <- factor(trade$Year_Month, levels = time_order, ordered = TRUE)

```

```{r}
singapore <- trade %>% group_by(Year_Month) %>% summarise(
  Exports = sum(Exports),
  Imports = -sum(Imports)
) %>% ungroup()

singapore <- singapore %>%
            mutate(BalanceOfTrade = (Exports+Imports))
singapore <- singapore %>%
            mutate(Trade_Volume = (Exports-Imports))
singapore<-transform(singapore,Balance=ifelse(BalanceOfTrade> 0,"Positive","Negative"))
```
```{r}
#write.csv(trade,"trade.csv", row.names = FALSE)
#view(singapore)
#seq(-60000000000,60000000000,10000000000)
```

```{r, echo = TRUE, warning = FALSE, message = FALSE}
fig <- singapore %>%
  plot_ly(
    y = ~Trade_Volume, 
    frame = ~Year_Month, 
     
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers',
    marker =list(size = 30, sizemode = "diameter")
  )
fig <- fig %>%
  layout(legend=list(title=list(text='Balance of Trade')),autosize = F, width = 300, height = 400)
fig <- fig %>%
  animation_opts(
    100, easing = 'elastic', redraw = TRUE
  )%>%animation_slider(hide = FALSE)

fig
```


```{r, echo = TRUE, warning = FALSE, message = FALSE}

fig <- trade %>%
  plot_ly(
    x = ~Exports, 
    y = ~Imports, 
    size = ~Trade_Volume, 
    color = ~Balance, 
    frame = ~Year_Month, 
    text = ~Country, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers',
    colors = c('maroon','darkturquoise'),
    marker =list(opacity = 0.9,sizemode = "diameter")
  )
fig <- fig %>%
  layout(legend=list(title=list(text='Balance of Trade')),autosize = F, width = 900, height = 500)
fig <- fig %>%
  animation_opts(
    1000, easing = 'elastic', redraw = FALSE
  )%>%animation_slider(hide = FALSE)

fig

```

```{r}
p <- ggplot(singapore, aes(x = Year_Month, text = paste0("Time: ", Year_Month))) +  geom_bar(singapore, mapping = aes(y=Exports, fill = "green"), stat = "identity")

p <- p + geom_bar(singapore, mapping = aes(y=Imports,  fill = "red" ), stat = "identity")



p <- p+geom_line(singapore, mapping = aes(x = Year_Month, y=BalanceOfTrade, group = 1))

p <- p +labs(title = "Singapore Trade Trend Jan (2018 to Jan 2022)", 
                     
                          subtitle = "Balance of Trade is positive",
                     x = 'Year Month', 
                     y ='Imports                   Exports')+
  scale_y_continuous(breaks = seq(-60000000000,60000000000,10000000000), labels=c("60B","50B","40B", "30B","20B","10B","0","10B","20B", "30B", "40B","50B","60B"))

p <- p + theme_bw() + theme(legend.position = "none",plot.title = element_text(size=10), 
                            plot.subtitle = element_text(size=9), axis.title = element_text(size=8, hjust=0.5), 
                            axis.text.x=element_text(size=6, vjust=0.5, angle = 45),  axis.text.y=element_text(size=6, vjust=0.5))+
  scale_fill_manual(values=c("#00CCCC", "#990033"))

ggplotly(p, tooltip = ("text"))
```

```{r}
trade <- trade %>% filter(Country == "Mainland China")

p <- ggplot(trade, aes(x=Year_Month, y=Imports, group = 1)) + geom_line()
p <- p +labs(title = "Singapore Trade Trend Jan (2018 to Jan 2022)", 
                     
                          subtitle = "Balance of Trade is positive",
                     x = 'Year Month', 
                     y ='Imports')+
  scale_y_continuous(breaks = seq(-60000000000,60000000000,10000000000), labels=c("60B","50B","40B", "30B","20B","10B","0","10B","20B", "30B", "40B","50B","60B"))

p <- p + theme_bw() + theme(legend.position = "none",plot.title = element_text(size=10), 
                            plot.subtitle = element_text(size=9), axis.title = element_text(size=8, hjust=0.5), 
                            axis.text.x=element_text(size=6, vjust=0.5, angle = 45),  axis.text.y=element_text(size=6, vjust=0.5))+
  scale_fill_manual(values=c("#00CCCC", "#990033"))

ggplotly(p, tooltip = ("text"))
```

```{r}
# Remove all regions in data
imports.remove <- c("Total Merchandise Imports","America", "Asia", "Europe", "Oceania", 
                    "European Union", "Germany, Democratic Republic Of",
                    "Democratic People's Republic Of Korea", "Yemen Democratic",
                    "Other Countries In America", "Other Countries In Oceania",
                    "Commonwealth Of Independent States", "Africa")

exports.remove <- c("Total Merchandise Imports","America", "Asia", "Europe", "Oceania", 
                    "European Union", "Germany, Democratic Republic Of",
                    "Democratic People's Republic Of Korea", "Yemen Democratic",
                    "Other Countries In Oceania", "Africa")

# For clustering
imports_clust <- imports %>% 
  select(`Data Series`, Time, Imports) %>%
  pivot_wider(names_from = Time, values_from = Imports)

imports_clust <- imports_clust[c(1:(nrow(imports_clust)-15)),]

import.countries <- c("Total Merchandise Imports", "America", "Asia", "Europe", "Oceania",
                      "Africa", "European Union", "Belgium", "Denmark", "France",
                      "Germany", "Greece", "Ireland", "Italy", "Luxembourg",
                      "Netherlands", "United Kingdom", "Portugal", "Spain", "Austria",
                      "Finland", "Norway", "Sweden", "Switzerland", "Liechtenstein",
                      "Malta", "Germany, Democratic Republic Of", "Hungary", "Poland", "Estonia",
                      "Latvia", "Lithuania", "Slovenia", "Czech Republic", "Slovakia",
                      "Brunei", "Indonesia", "Malaysia", "Philippines", "Thailand",
                      "Myanmar", "Cambodia", "Laos", "Vietnam", "Japan",
                      "Hong Kong S.A.R.", "South Korea", "Taiwan", "Macao S.A.R", "China",
                      "Democratic People's Republic Of Korea", "Afghanistan", "Bangladesh", "India", "Maldives",
                      "Nepal", "Pakistan", "Sri Lanka", "Bahrain", "Cyprus",
                      "Iran", "Israel", "Jordan", "Kuwait", "Lebanon",
                      "Oman", "Qatar", "Saudi Arabia", "Syria", "United Arab Emirates",
                      "Yemen", "Yemen Democratic", "Canada", "Puerto Rico", "United States of America",
                      "Argentina", "Brazil", "Chile", "Colombia", "Ecuador",
                      "Mexico", "Paraguay", "Peru", "Uruguay", "Venezuela",
                      "Netherlands Antilles", "Panama", "The Bahamas", "Bermuda", "French Guiana",
                      "Grenada", "Guatemala", "Honduras", "Jamaica", "Saint Vincent and the Grenadines",
                      "Trinidad & Tobago", "Anguilla", "Other Countries In America", "Australia", "Fiji",
                      "Nauru", "New Caledonia", "New Zealand", "Papua New Guinea", "Cocos",
                      "French Southern and Antarctic Lands", "Norfolk Island", "Cook Islands", "French Polynesia", "Guam",
                      "Kiribati", "Niue", "Solomon Islands", "Tuvalu", "Wallis and Futuna",
                      "Federated States of Micronesia", "Palau", "South Sudan", "Other Countries In Oceania", "Commonwealth Of Independent States"
                      )

exports_clust <- exports %>% 
  select(`Data Series`, Time, Exports) %>%
  pivot_wider(names_from = Time, values_from = Exports)

exports_clust <- exports_clust[c(1:(nrow(exports_clust)-15)),]

export.countries <- c("Total Merchandise Imports", "America", "Asia", "Europe", "Oceania",
                      "Africa", "European Union", "Belgium", "Denmark", "France",
                      "Germany", "Greece", "Ireland", "Italy", "Luxembourg",
                      "Netherlands", "United Kingdom", "Portugal", "Spain", "Austria",
                      "Finland", "Sweden", "Switzerland", "Malta", "Germany, Democratic Republic Of", 
                      "Hungary", "Poland", "Estonia", "Latvia", "Lithuania", 
                      "Slovenia", "Czech Republic", "Slovakia", "Brunei", "Indonesia", 
                      "Malaysia", "Philippines", "Thailand", "Myanmar", "Cambodia", 
                      "Laos", "Vietnam", "Japan", "Hong Kong S.A.R.", "South Korea", 
                      "Taiwan", "Macao S.A.R", "China", "Democratic People's Republic Of Korea", "Afghanistan", 
                      "Bangladesh", "India", "Maldives", "Nepal", "Pakistan", 
                      "Sri Lanka", "Bahrain", "Cyprus", "Iran", "Israel", 
                      "Jordan", "Kuwait", "Lebanon", "Oman", "Qatar", 
                      "Saudi Arabia", "Syria", "United Arab Emirates", "Yemen", "Yemen Democratic", 
                      "Canada", "Puerto Rico", "United States of America", "Argentina", "Brazil", 
                      "Chile", "Colombia", "Ecuador", "Mexico", "Paraguay", 
                      "Peru", "Uruguay", "Venezuela", "Australia", "Fiji", 
                      "New Caledonia", "New Zealand", "Papua New Guinea", "French Polynesia", "Guam", 
                      "Solomon Islands", "Other Countries In Oceania"
                      )

# Date range for slider in app
date.range <- names(imports_clust)[-1]
  # Reverse values to start with earliest date
date.range <- date.range[c(length(date.range):1)]

#Functions to be used
arrange.data <- function(df, countries){
  df$Countries <- countries
  df <- df[, c(ncol(df):2)]
  return(df) 
}

filter.data <- function(df, start_date, end_date){
  index.end <- grep(end_date, colnames(df))
  index.start <- grep(start_date, colnames(df))
  
  df <- df[c(index.start:index.end)]
  
  return(df)
}

convert_df <- function(df, countries){
  df <- data.frame(df)
  rownames(df) <- countries
  df <- df[-1,]
  return(df)
}

remove.regions <- function(df, rows.remove){
  rows_to_remove <- which(row.names(df) %in% rows.remove)
  
  df <- df[-rows_to_remove,]
  return(df)
}

prep.data <- function(df){
  df <- df %>% 
    mutate_all(~as.numeric(as.character(.))) 
  
  clust.norm <- BBmisc::normalize(df, method="standardize")
  return(clust.norm)
}

clustering <- function(clust.norm, type, k, method){
  if (type == "PAM"){
    clust.result <- tsclust(clust.norm, type="partitional", k=k, distance="dtw", centroid="pam")
  }
  else{
    clust.result <- tsclust(clust.norm, type = "h", k = k, distance = "dtw", 
                            centroid=shape_extraction, control = hierarchical_control(method = method),
                            seed = 2022)
  }
  return(clust.result)
}

plot.clust <- function(clust.result, dataType, clustType){
  plot(clust.result, type = "sc") +
    xlab("Time") +
    ylab(dataType) +
    theme(
      panel.spacing.y = unit(0, 'lines'),
      axis.ticks.y = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks.x = element_blank(),
      axis.text.x = element_blank()
    ) +
    ggtitle(label = paste("Clustering Results using", clustType, sep = " "))
}

plot.dendro <- function(clust.result, dataType){
  hcdata <- ggdendro::dendro_data(clust.result)
  
  names_order <- hcdata$labels$label
  
  hcdata %>%
    ggdendro::ggdendrogram(., rotate=FALSE, leaf_labels=FALSE) +
    scale_y_continuous(expand = c(0.02, 0)) +
    ggtitle(paste("Dendrogram Results for Hierarchical Clustering for", dataType, sep = " "),
            "Shows how the clusters are formed")
}

plot.clustmap <- function(clust.final, dataType){
  world <- ne_countries(scale = "medium", returnclass = "sf") 
  clust.map <- merge(world, clust.final, by.x="admin", by.y="Countries")
  clust.map$Clusters <- as.factor(clust.map$Clusters)
  
  clust_worldmap <- ggplot(clust.map) + 
    geom_sf_interactive(
      aes(fill = Clusters,
          tooltip = admin,
          data_id = admin)
    ) +
    theme_map() +
    ggtitle("DTW Time Series Clustering Results using Map",
            paste("Shows the clustering analysis of the different countries for", dataType, sep = " "))
  
  clust_worldmap <- girafe(code, 
                           ggobj = clust_worldmap,
                           options = list(opts_tooltip(use_fill = TRUE),
                                          opts_zoom(min = 1, max = 5),
                                          opts_toolbar(saveaspng = FALSE)))
  
  clust_worldmap
}

```

```{r, echo = TRUE, warning = FALSE, message = FALSE}
ui <-
  dashboardPage(
  skin = 'black',
  dashboardHeader(title = "Singapore Trade"),         
  
  dashboardSidebar(
    sidebarMenu(
      menuItem("Introduction", tabName = "Intro", icon = icon('globe')),
      menuItem("Exploratory module", tabName = "EDA", icon = icon('chart-bar')),
      menuItem("Time Series Clustering", tabName = "Clustering", icon = icon('chart-line'))
    )
  ),
  dashboardBody(
    tabItems(
      tabItem("Intro",
              fluidPage(theme = shinytheme('yeti'), 
                        titlePanel("Partners through the Pandemic"),
                        fluidRow(column(width = 6,
                                 tags$img(src = 'image.jpg',width = 500, height = 400)),
                          column(width = 6,
                                 h4('About the Application'),
                                 p("This is an interactive application built in R Shiny. The application aims to provide its users with a user-friendly interface to see how the imports, exports and balance of trade with countries across the globe varied for Singapore during the Coronavirus pandemic. Additionally the application also provides the users to view clustering patterns for the countries in terms of their trade with Singapore during the Pandemic through Time-Series Clustering."),
                                 p('The data set was downloaded from the Department of Statistics Singapore. It contains the monthly import and export values between Singapore and its trading partners. This application focuses on the time-period from January 2018 to January 2022 which helps in studying the trading trends during the pandemic.'),
                                 
                                   
                                 )
                          )
                        )
              )
      ,
tabItem("EDA",
              tabsetPanel(
                tabPanel("Dataset Summary"
                         
                ),
tabPanel("Overall Trade",fluidPage(
                           titlePanel("Mapping Airbnbs"),
         
         sidebarLayout(
    sidebarPanel(
      
      # Add a slider selector for years to filter
      sliderTextInput(inputId = "Time", "Select a Time-Interval", singapore$Year_Month, selected = singapore$Year_Month[c(1, length(singapore$Year_Month))])
    ),
    mainPanel(
    
  plotlyOutput(outputId = "g", width = "50%"))))),

tabPanel("Exploratory",
  plotlyOutput(outputId = "p", width = "70%")
))),

tabItem("Clustering",
              
tabPanel(
        "Time Series Clustering",
        sidebarLayout(
          sidebarPanel(
            width = 3,
            selectInput(inputId = "dataType",
                        label = "Trade Type:",
                        choices = c("Imports" = "Imports",
                                    "Exports" = "Exports"
                                    ),
                        selected = "Imports"),
            sliderTextInput(
                        inputId = "dateSlider",
                        label = "Date Range:",
                        choices = date.range,
                        selected = date.range[c(1, length(date.range))]
            ),
            numericInput(
              inputId = "nClusters",
              label = "Number of Clusters:",
              min = 2,
              max = 15,
              step = 1,
              value = 6
            ),
            selectInput(
              inputId = "clustType",
              label = "Clustering Method:",
              choices = c("PAM", "Hierarchical"),
              selected = "PAM"
            ),
            uiOutput(
              outputId = 'disableHmethod'
            ),
            actionButton(
              inputId = "submitChanges",
              label = "Apply Changes"
            )
          ),
          mainPanel(
            plotOutput("clustPlot"),
            girafeOutput(
              outputId = "worldMap"
            ),
            plotOutput(
              outputId = "dendroPlot"
            )
          )
        )
      )))))

server <- function(input, output, session) {
  
  
  
  
  output$out_year <- renderText(input$Time)
  
  
  output$g <- renderPlotly({
    
    singapore <- singapore[singapore$Year_Month>=input$Time[1] & singapore$Year_Month<=input$Time[2],]
    
    p <- ggplot(singapore, aes(x = Year_Month, text = paste0("Time: ", Year_Month))) +  geom_bar(singapore, mapping = aes(y=Exports, fill = "green"), stat = "identity")

p <- p + geom_bar(singapore, mapping = aes(y=Imports,  fill = "red" ), stat = "identity")



p <- p+geom_line(singapore, mapping = aes(x = Year_Month, y=BalanceOfTrade, group = 1))

p <- p +labs(title = "Singapore Trade Trend Jan (2018 to Jan 2022)", 
                     
                          subtitle = "Balance of Trade is positive",
                     x = 'Year Month', 
                     y ='Imports                   Exports')+
  scale_y_continuous(breaks = seq(-60000000000,60000000000,10000000000), labels=c("60B","50B","40B", "30B","20B","10B","0","10B","20B", "30B", "40B","50B","60B"))

p <- p + theme_bw() + theme(legend.position = "none",plot.title = element_text(size=10), 
                            plot.subtitle = element_text(size=9), axis.title = element_text(size=8, hjust=0.5), 
                            axis.text.x=element_text(size=6, vjust=0.5, angle = 45),  axis.text.y=element_text(size=6, vjust=0.5))+
  scale_fill_manual(values=c("#00CCCC", "#990033"))

p <- ggplotly(p, tooltip = ("text"))
    
  })
  
  
  
  output$p <- renderPlotly({
    fig <- trade %>%
  plot_ly(
    x = ~Exports, 
    y = ~Imports, 
    size = ~Trade_Volume, 
    color = ~Balance, 
    frame = ~Year_Month, 
    text = ~Country, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers',
    colors = c('maroon','darkturquoise'),
    marker =list(opacity = 0.9,sizemode = "diameter")
  )
fig <- fig %>%
  layout(legend=list(title=list(text='Balance of Trade')),autosize = F, width = 900, height = 500)
fig <- fig %>%
  animation_opts(
    1000, easing = 'linear', redraw = FALSE, transition = 100
  )%>%animation_slider(hide = FALSE)
  })
  

  # Only show select input for Hierarchical control method when selected
  output$disableHmethod <- renderUI({
    if (input$clustType == "Hierarchical"){
      selectInput(
        inputId = "hierControl",
        label = "Hierarchical Control Method:",
        choices = c("complete", "single", "average",
                    "ward.D", "ward.D2"),
        selected = "complete"
      )
    }
    else{
      return(NULL)
    }
  })
  
  # Get data out for clustering based on user input
  a <- reactiveValues()
  
  observeEvent(
    input$submitChanges,
    {
      if(input$dataType == "Imports"){
        clust_2 <- arrange.data(imports_clust, import.countries)
        clust.countries <- import.countries
        rows.remove <- imports.remove
      }
      else{
        clust_2 <- arrange.data(exports_clust, export.countries)
        clust.countries <- export.countries
        rows.remove <- exports.remove
      }
      
      clust_2 <- filter.data(clust_2, input$dateSlider[1], input$dateSlider[2])
      clust_3 <- convert_df(clust_2, clust.countries)
      clust_3 <- remove.regions(clust_3, rows.remove)
      
      #Normalise data
      clust.norm <- prep.data(clust_3)
      
      #Do clustering
      if (input$clustType == "Hierarchical"){
        control <- input$hierControl
      }
      else{
        control <- ""
      }
      clust.result <- clustering(clust.norm, input$clustType, input$nClusters, control)
      
      
      a$clust_result <- clust.result
      a$filtered_countries <- row.names(clust_3)
    }
  )
  
  output$clustPlot <- renderPlot({
    input$submitChanges
    req(a$clust_result)
    req(a$filtered_countries)
    
    isolate(plot.clust(a$clust_result, input$dataType, input$clustType))
  })
  output$worldMap <- renderGirafe({
    input$submitChanges
    req(a$clust_result)
    req(a$filtered_countries)
    
    clust.final <- isolate(data.frame(Countries=a$filtered_countries, Clusters=a$clust_result@cluster))
    isolate(plot.clustmap(clust.final, input$dataType))
  })
  # Only show dendrogram for Hierarchical
  output$dendroPlot <- renderPlot({
    if (input$clustType == "Hierarchical"){
      input$submitChanges
      req(a$clust_result)
      req(a$filtered_countries)
      
      isolate(plot.dendro(a$clust_result, input$dataType))
    }
    else{
      return(NULL)
    }
  })
}

# Run the application 
shinyApp(ui = ui, server = server)
```





